version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - ./.env
volumes:
  postgres_data: